<a href="https://colab.research.google.com/github/TEJASREE-PASALUR/Python-Edube/blob/main/Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ipynb=Interactive python notebook
#py=python
#hashtag(#) represents comment
# to run any cell---->ctrl+enter,shift+enter,alt+enter

In [ ]:
#python programming

In [ ]:
print("Hello World!")

Hello World!


In [ ]:
# Sequences in Python
# Unlinke variables these store values not only for one but stores for many
# Ex:Lists=[Ordered, mutables and allow duplicates]
#Tuples=(Ordered and immutable-can't be changed using operations)
#Sets={Unordered}
#Dictionaries={key1:value 1,key2:value2,....}

In [ ]:
#list[]
a=[1,4,6,7]
print (a)

[1, 4, 6, 7]


In [ ]:
a

[1, 4, 6, 7]

In [ ]:
b=['hai',30,True,20.5]
print (b)

['hai', 30, True, 20.5]


In [ ]:
fruits=['apple','banana','cherry']
print (fruits)

['apple', 'banana', 'cherry']


In [15]:
fruits.append('Pine apple')
print (fruits)

['apple', 'banana', 'cherry', 'Pine apple', 'Pine apple', 'Pine apple']


In [13]:
fruits.insert(2,'Blue berry')
print(fruits)

['apple', 'banana', 'Blue berry', 'cherry', 'Pine apple', 'Pine apple']


In [21]:
fruits.remove('Pine apple')
print(fruits)

['apple', 'cherry', 'Pine apple', 'Pine apple']


In [27]:
fruits.append('Orange')
print(fruits)

['apple', 'cherry', 'Orange']


In [28]:
fruits.insert(3,'Guava')
print(fruits)

['apple', 'cherry', 'Orange', 'Guava']


In [29]:
fruits.pop(0)
print(fruits)

['cherry', 'Orange', 'Guava']


In [30]:
fruits.reverse()
print(fruits)

['Guava', 'Orange', 'cherry']


In [34]:
fruits[0]

'Guava'

In [36]:
fruits[-1]

'cherry'

In [37]:
fruits[0:2] # starts from zero element and stops before 2nd element

['Guava', 'Orange']

In [38]:
fruits[0:-1] # includes zero element and doesnot include the last element i.e, stops before the last element

['Guava', 'Orange']

In [39]:
# 5 operations of list
# list.append('string')=adds the variable to the list
#list.insert(int,'string)=adds the variable at the desired index i.e, int
#list.remove('String')=removes the element from the list
#list.pop(int)=removes element from the list at the desired index
#list.reverse()=reverse the complete list

In [ ]:
#TUPLES=very much faster and efficient when compared to list bt due to immutable nature not prefferred

In [40]:
a=(1,2,3,4,5)
print(a)
type(a)

(1, 2, 3, 4, 5)


tuple

In [41]:
b=(55,True,'Teja')
print (b)

(55, True, 'Teja')


In [42]:
b

(55, True, 'Teja')

In [44]:
b.insert(3,'Lasya')
print(b)

AttributeError: 'tuple' object has no attribute 'insert'

In [ ]:
#Tuples= We can't change element in tuple bt we can change them during creating them at first

In [ ]:
#Set={} contaions only variables or numbers seperated by ,

In [45]:
a={1,4,5,77,8}
print(a)
type(a)

{1, 4, 5, 8, 77}


set

In [46]:
b={4,5,7,9,12,45}
print(b)

{4, 5, 7, 9, 12, 45}


In [48]:
c=a|b  ## a union b
c

{1, 4, 5, 7, 8, 9, 12, 45, 77}

In [49]:
d=a&b ## a intersection b
d

{4, 5}

In [ ]:
#DICTIONARIES={key:value,key1:value1,...etc...} contains both key value and elements

In [55]:
dict={'first':'Teja','last':'sree'}
type(dict)
print(dict)

{'first': 'Teja', 'last': 'sree'}


In [ ]:
# PYTHON LIBRARIES--->Collection of Modules
#Ex: NUMPY,PANDAS,MATLPLOTLIB,SKLEARN,OPENCV,etc...

In [ ]:
#NUMPY-->Numerical Python
#--->used insted of list
#---->this is much more faster and efficient than lists

In [60]:
import numpy as np  #np is just a variable if you want to change u can change it to any thing u want.
a=np.array(1)  # scalar--->zero dimensions
a

array(1)

In [61]:
a.shape #no rows and coloums

()

In [65]:
a.ndim # dimensions in the variable

0

In [64]:
a.size # show the number of elements in the given variable

1

In [66]:
a=np.array(1) # scalar -->zero dimensional
b=np.array([1,2,3,4,5,6,7]) # vector -->1 dimmensional
b

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
b.shape #represents that 7 coloums and 1 row

(7,)

In [69]:
b.ndim # 1 Dimensional means a vector

1

In [70]:
b.size

7

In [79]:
a=np.array(1) #--->0 dimensional
b=np.array([1,24,56,78,9,0]) #--->1 dimensional(coloums*rows)
c=np.array([[1,2,34],[3,4,56]]) #---->2 dimensional(rows*coloums)
print("a=",a)
print("b=",b)
print("c=",c)

a= 1
b= [ 1 24 56 78  9  0]
c= [[ 1  2 34]
 [ 3  4 56]]


In [80]:
c.size

6

In [81]:
c.shape   # 2 rows and 3 coloums

(2, 3)

In [82]:
c.ndim # 2 dimensions --->MATRIX

2

In [96]:
np.random.seed(0) ## keeps the firstly generated value as permanent set
## np=numpy-->numerical python : random= collection of libraries : randint()= range of  libraries and how many numbers u need
d=np.random.randint(10,50,10) # from the range (10,50), i need 10 numbers
print("d=",d)

d= [32 23 34 13 14 33 45 12 33 39]


In [97]:
d.size

10

In [98]:
d.shape ## 10 coloums and 1 row

(10,)

In [100]:
d.ndim

1

In [106]:
d=d.reshape(2,5) ## 2*5 = total elements
print("new_d=",d)

d= [[32 23 34 13 14]
 [33 45 12 33 39]]
new_d= [[32 23 34 13 14]
 [33 45 12 33 39]]


In [102]:
d.reshape(5,2) ## 5*2=total elements

array([[32, 23],
       [34, 13],
       [14, 33],
       [45, 12],
       [33, 39]])